### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [JonDoNym/peinjector#2]
I would like to point out that identifiers like "[`_PEINFECT_METHOD`](https://github.com/JonDoNym/peinjector/blob/5bb5ced72ace17c186978dac214844655eb7d15e/peinjector/libpeinfect.h#L21)" and "[`_PECONFIG`](https://github.com/JonDoNym/peinjector/blob/5bb5ced72ace17c186978dac214844655eb7d15e/peinjector/libpeserver.h#L55)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by JonDoNym** [comment]
This seems to be true. The "_" prefix is somewhat like an personal preference of mine, I use it since years. I'm using it for internal-use-functions or, like in this case, for structures which will only be used by their typedef.

I understand your point, I'll think about it, but there is no guarantee that it will be modified.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106)?
